### ISSUE TITLE
Plugin conflicts with the Cheats AS plugin.

### ISSUE THREAD

**Issue by danylopez123** [wootguy/ghosts#1]
Before of the fall of the Sven Coop forums, i downloaded a cheats plugin witch you can use cheats without the sv_cheats command.

However, any cheat that starts with G, when i try to do a command like .giveall or .god it will says the .ghosts commands in chat and the previous commands i mentioned wont work.

**Comment by wootguy** [comment]
I'll fix this later, but for now you can either:
- Type the commands in console instead of chat.
- Set [this value](https://github.com/wootguy/ghosts/blob/master/ghosts.as#L15) to false
